import { Employee, RoleId } from "@/types";
import { v4 as uuidv4 } from "uuid";

const EMPLOYEE_DATA: Record<RoleId, string[]> = {
  sala: [
    "SIMON",
    "LUISA",
    "NOEMI",
    "ANIKA",
    "ANNALISA",
    "TINA",
    "MATTIA MURO",
    "MATTIA REGI",
    "BERICA",
    "LU",
    "MONICA B",
    "LEO",
    "CELESTE",
    "NICOLE",
    "CLAUDIA",
    "GIORGIA PIZ",
    "ALI",
    "REBECCA",
    "PICCOLI",
    "MAXI",
    "PIZZATO",
    "ROXANA",
    "CINZIA",
    "BETTY",
    "ROBERTA",
    "SOPHIE",
    "DAVIDE ZUC",
    "SILVIA",
    "NICOLE",
    "TASCA",
    "CHECCO",
    "EDO",
    "RIKI PASI",
    "RIKI GERE",
    "ELISA CAM VECC",
    "PEDRO",
    "GLORIA CIT",
    "EDOARDO AMICO ANNALI",
    "SANA",
    "LORENZO BOCIA",
    "BRANDO",
    "ANDY",
    "ANNAMARIA",
    "CRISTIAN FRACC",
    "GIACOMO MORESC",
    "FRATELLO REBE",
    "IRIS",
    "LINDA",
    "LORENZO AMICO CHECC",
    "MATTEO BEST",
    "SOFIA BEST",
    "BORDI",
    "BORDI FRATELLO",
    "REMA",
    "GIULIA GUERRA",
    "SOFIA PD++",
    "ALE PD++",
    "SADULA",
    "DEBORA",
    "MAURO",
    "YAYA",
    "STEVEN",
    "FRATELLO STEVEN",
    "DIEGO VENEZIA",
    "BERGA (CAM DISCO)",
    "CELI",
    "THOMAS GIASI",
    "JORGEN",
    "DARIO",
    "JACOPO",
    "CELI",
  ],
  bar: [
    "NICOLA",
    "PIERO",
    "DAVIDONE",
    "ALBY",
    "GIULIA",
    "FEDE",
    "NICHOLAS",
    "GIADA",
    "BEATRICE",
    "SIMONE",
    "CRISTIAN",
    "OLLY",
    "LARA",
    "GIADA VECCHIA",
    "MARTINA",
    "FEDE AUTO",
    "KEITA",
    "NICOLE CARLINO",
    "PICCOLI",
    "MARY MURETTO",
    "PROFESSORE ALE",
    "SAMUELE",
    "ALBERTO",
  ],
  cassa: [
    "SHABI",
    "FIORINDA",
    "ALE BAGGIO",
    "ALESSIA ZAB",
    "TIZIANA",
    "ALICE CREM",
    "GLORIA",
    "DILETTA",
    "REBECCA AISHA",
    "PANDA",
    "LUDO",
    "MARTA BRUSA",
    "ANNA BRUSA",
    "ESTER",
    "MIA",
    "SVEVA",
    "CLAUDIA",
    "ARIANNA CALZAVA",
    "MAREVA",
    "BEA MASACOTTO",
  ],
  pass: ["ELENA", "GIADA PONTA", "IRIS", "AISHA"],
  guardaroba: [
    "KATIA",
    "SARA",
    "RAMELA",
    "SORELLA MATTIA",
    "ROSA",
    "SORELLA ALE",
    "FIGLIE MONICA",
    "MATILDE",
    "MARGHERITA",
    "ZOE",
    "BORTOLLA",
    "LAILA",
    "ALESSIA PAROLIN (AMICA PAMELA)",
  ],
};

export function generateSeedEmployees(): Employee[] {
  const employees: Employee[] = [];
  for (const [role, names] of Object.entries(EMPLOYEE_DATA)) {
    for (const name of names) {
      employees.push({
        id: uuidv4(),
        name,
        role: role as RoleId,
        active: true,
      });
    }
  }
  return employees;
}
